name: "Fetch pp"

on:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run get_pp.py
        run: |
          pip install -r requirements.txt
          python3 ./get_pp.py
      
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add -a
          git commit -m "Update chart"
          git push
